= TP Inicial - Laboratorio de Construcción de Software - Entrega 4
Ebertz Ximena <xebertz@campus.ungs.edu.ar>; Gross Pablo <pablorubengross@gmail.com>; López Gonzalo <gonzagonzalopez20@gmail.com>
v1, {docdate}
:toc:
:title-page:
:toc-title: Secciones
:numbered:
:source-highlighter: coderay
:tabsize: 4
:nofooter:
:pdf-page-margin: [3cm, 3cm, 3cm, 3cm]

== Introducción

En este documento, abordaremos los distintos pasos y los problemas surgidos en la implementación en la nube de nuestro modelo de clasificación de lunares. Explicaremos por qué debimos realizar un cambio en la arquitectura de nuestro modelo, motivo estrictamente relacionado con los datos utilizados para el entrenamiento. Finalmente, analizaremos el nuevo modelo y su implementación en la nube.

== Desarrollo

Como primer paso, partiendo desde nuestro modelo convolucional generado en la _entrega 3_, procedimos a su implementación en la nube.

.arquitectura de la red convolucional generada en la tercer entrega
[source, python]
----
modelo_cnn = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(16, (3, 3), activation = 'relu', input_shape = (100, 100, 3)),
    tf.keras.layers.MaxPooling2D(3, 3),

    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(64, activation = 'relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(32, activation = 'relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(1, activation = 'sigmoid')
])

#Compilación
modelo_cnn.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

----

Este modelo tiene una precisión del 85%, y un nivel de error de menos del 40%, lo que lo hace lo suficientemente bueno para su implementación. Sin embargo, nos encontramos con un nuevo problema: el modelo no era lo suficientemente preciso con imágenes brindadas por el usuario. Las predicciones tendían a ser mayoritariamente malignas, con lunares benignos. Esto hizo que realicemos distintas pruebas para mejorar su precisión y corregir esta tendencia.

=== Pruebas

=== Nuevos datos

=== Nuevo modelo

=== Pruebas

=== Implementación en la nube

== Conclusión