= TP Inicial - Laboratorio de Construcción de Software
Ebertz Ximena <xebertz@campus.ungs.edu.ar>; Gross Pablo <pablorubengross@gmail.com>; López Gonzalo <gonzagonzalopez20@gmail.com>
v1, {docdate}
:toc:
:title-page:
:toc-title: Secciones
:numbered:
:source-highlighter: highlight.js
:tabsize: 4
:nofooter:
:pdf-page-margin: [3cm, 3cm, 3cm, 3cm]

== Introducción

En el transcurso de este documento, se abordará de manera exhaustiva el proceso de preparación de los datos destinados a alimentar nuestri sistema de detección de enfermedades oculares. Además, se proporcionarán argumentos sólidos que respaldan la elección de un modelo de _Machine Learning_ específico. Finalmente, se arrojará luz sobre el funcionamiento intrínseco del proceso de entrenamiento de dicho modelo.

== Desarrollo

=== Detección de retinopatia diabetica

Nuestro sistema está destinado a la detección de retinopatias diabeticas y su severidad a través del análisis de imágenes de fondo de ojo, tanto en el lado derecho como en el izquierdo, provenientes de un conjunto de datos de pacientes reales.

Para desarrollar el sistema estamos utilizando Google Colab, el cual es un servicio en línea gratuito ofrecido por Google que permite a los usuarios escribir y ejecutar código de Python en un entorno de bloc de notas basado en la nube.

=== Datos

==== Exploración de datos
El conjunto de datos que disponemos consta de 35.108 imagenes de fondo de ojos de paciente reales, junto con los niveles de severidad de la "rinopatia diabetica" diagnosticada por profecionales medicos. Estos datos se encuentran en el archivo trainLabels_cropped.csv trainLabels_cropped.csv.

El archivo mencionado cueanta con 4 columnas las cuales la primera no tiene nombre, la Segunda es "unnamed:0", la tercera es "image" y la ultima se llama "level".

A su ves dejamos 1.000 imagenes de fondo de ojos ya diagnosticadas aparte para poder verificar la precision del modelo que estamos presentando, al comparar le prediccion del modelo con el diagnostico actual.

//El conjunto de datos del que disponemos consta de 6392 imágenes de fondos de ojos pertenecientes a pacientes reales, junto con los diagnósticos correspondientes proporcionados por médicos especializados. Estos diagnósticos se encuentran registrados en el archivo `full_df.csv`.

//El archivo mencionado anteriormente cuenta con 19 columnas, las cuales son: "ID", "Patient Age", "Patient Sex", "Left-Fundus", "Right-Fundus", "Left-Diagnostic Keywords", "Right-Diagnostic Keywords", "N", "D", "G", "C", "A", "H", "M", "O", "filepath", "labels", "target" y "filename".

//Por otra parte, poseemos mil imágenes adicionales de fondos de ojos tomadas de pacientes que aún no han sido diagnosticados. Estas imágenes serán utilizadas con el propósito de que nuestro sistema de inteligencia artificial genere sus propios diagnósticos en relación a las mismas posteriormente.

==== Preparación de datos

A los datos presentes observamos que las primeras dos columans de informacion son superfluas ya que no aportan informacion util para el modelo. Por esto las sacamos del modelo y las ignoramos.

Con las otras dos columans de informacion que nos quedan podemos distinguir la imagen que se quiere analizar y la "severidad de la rinopatia diabetica", esta empieza desde 0, implicando que no la padece hasta 4 que la padece severamente.

=== Selección de modelo

Por este caso mismo de analizis de imagenes recurrimos a utilizar el modelo de "Deep Learning con redes neuronales convolucionales" el cual es optimo para estos mismos. Esto se deve a la capacida de la red neuronal convolutiva de poder segmentar y enfocar aplicando contexto con ecuaciones en los nodos. Permitiendo asi el analisis de una imagen compleja de manera rapida.

El analisis completo de las imagenes es posible por las capas convolutivas de la red neuronal. Estas capas agarran un pixel de la imagen y se aplican filtros a los pixeles subjasentes para determinar su utilidad al modelo. despues se agrupan los pixeles en cuadrados del tamaño que uno determine (en nuestro caso 2x2) y en esos grupos de pixeles se extrae el de mayor valor, generando asi una imagen de donde se resalten las caracteristicas necesarias para el modelo.

=== Entrenamiento de modelo

El modelo que se encuentra en uso utiliza una red neuronal de 10 capas las cuales 4 de ellas son convolucionales. Este mismo modelo se encarga de consumir imagenes de fondos de ojos para poder determinar la seriedad de la rinopatia diabetica a traves del analizis de patrones encontrados en las imagenes con las cuales el modelo alla entrenado.

Esto se produce al ingresar las imagenes a la red neuronal para que pueda distinguir patrones que se enceuntren en varias imagenes presentadas con su diagnostico ya presente.

== Dificultades
(expandir despues)

Entrada de datos para entrenar el modelo

que los resultados tengan sentido en el modelo de la IA


== Conclusión


