= TP Inicial - Laboratorio de Construcción de Software
Ebertz Ximena <xebertz@campus.ungs.edu.ar>; Gross Pablo <pablorubengross@gmail.com>; López Gonzalo <gonzagonzalopez20@gmail.com>
v1, {docdate}
:toc:
:title-page:
:toc-title: Secciones
:numbered:
:source-highlighter: highlight.js
:tabsize: 4
:nofooter:
:pdf-page-margin: [3cm, 3cm, 3cm, 3cm]

== Introducción

En el transcurso de este documento, se abordará de manera exhaustiva el proceso de preparación de los datos destinados a alimentar nuestro sistema de detección de enfermedades oculares. Además, se proporcionarán argumentos sólidos que respaldan la elección de un modelo de _Machine Learning_ específico. Finalmente, se arrojará luz sobre el funcionamiento intrínseco del proceso de entrenamiento de dicho modelo.

== Desarrollo

=== Detección de Retinopatía Diabética

Nuestro sistema está destinado a la detección de retinopatías diabéticas y su severidad a través del análisis de imágenes de fondo de ojo, tanto en el lado derecho como en el izquierdo, provenientes de un conjunto de datos de pacientes reales.

Para desarrollar el sistema estamos utilizando Google Colab, el cual es un servicio en línea gratuito ofrecido por Google que permite a los usuarios escribir y ejecutar código de Python en un entorno de bloc de notas basado en la nube.

=== Datos

==== Exploración de datos

El conjunto de datos que disponemos consta de 35.126 imágenes de fondo de ojos de paciente reales, junto con los niveles de severidad de la retinopatía diabética diagnosticada por profesionales médicos. Estos datos se encuentran en el archivo `trainLabels.csv`.

El archivo mencionado cuenta con 2 columnas, las cuales son `image` y `level`.

//A su vez, dejamos 1.000 imágenes de fondo de ojos ya diagnosticadas aparte para poder verificar la precisión del modelo que estamos presentando, al comparar le predicción del modelo con el diagnostico actual.

==== Preparación de datos

//A los datos presentes observamos que las primeras dos columnas de información son superfluas ya que no aportan información útil para el modelo. Por esto las sacamos del modelo y las ignoramos.

Con las dos columnas de información del archivo podemos distinguir la imagen que se quiere analizar y la "severidad de la retinopatía diabética", esta empieza desde 0, implicando que no la padece hasta 4 que la padece severamente.

=== Selección de modelo

Por este caso mismo de análisis de imágenes recurrimos a utilizar el modelo de "Deep Learning con redes neuronales convolucionales" el cual es optimo para estos mismos. Esto se debe a la capacidad de la red neuronal convolutiva de poder segmentar y enfocar aplicando contexto con ecuaciones en los nodos. Permitiendo así el análisis de una imagen compleja de manera rápida.

El análisis completo de las imágenes es posible por las capas convolutivas de la red neuronal. Estas capas agarran un pixel de la imagen y se aplican filtros a los pixeles subyacentes para determinar su utilidad al modelo. Después se agrupan los pixeles en cuadrados del tamaño que uno determine (en nuestro caso 2x2) y en esos grupos de pixeles se extrae el de mayor valor, generando así una imagen de donde se resalten las características necesarias para el modelo.

=== Entrenamiento de modelo

El modelo que se encuentra en uso utiliza una red neuronal de 10 capas las cuales 4 de ellas son convolucionales. Este mismo modelo se encarga de consumir imagenes de fondos de ojos para poder determinar la seriedad de la rinopatia diabetica a traves del analizis de patrones encontrados en las imagenes con las cuales el modelo alla entrenado.

Esto se produce al ingresar las imagenes a la red neuronal para que pueda distinguir patrones que se enceuntren en varias imagenes presentadas con su diagnostico ya presente.

== Dificultades

=== Entrada de datos para entrenar el modelo

    Hubo conflictos con la manera en la que consumiamos los datos, de tal forma que no se podia entrenar el modelo por que los datos no se encontraban en el formato que el modelo pedia

=== Que los resultados tengan sentido en el modelo de la IA

    Una ves entrenado el modelo se trato de verificar su precision pero este en ves de dar resultados de 0 o 1. Para determinar la enfermedad ocular presente daba un valor superior a 1

=== Cambio de Dataset

    Se cambio el dataset para poder tratar de generar un modelo mas preciso

=== Presicion del modelo

    El modelo entrenado con el nuevo dataset presente puede entrenar por varias Epoch y aun no superar el 0,4624 de presicion

== Conclusión

    