= TP Inicial - Laboratorio de Construcción de Software
Ebertz Ximena <xebertz@campus.ungs.edu.ar>; Gross Pablo <...>; López Gonzalo <gonzagonzalopez20@gmail.com>
v1, {docdate}
:toc:
:title-page:
:toc-title: Secciones
:numbered:
:source-highlighter: coderay
:tabsize: 4
:nofooter:


== Introducción

Investigación de conceptos: IA, Machine Learning, Deep Learning.

Investigación de proyectos de Data Science o Big Data.

== Objetivo

Acá va el objetivo.

== Repositorio

Acá va el link.

== Desarrollo

=== Inteligencia Artificial (IA)

Le llamamos "inteligencia artificial" o "IA" a los sistemas informáticos que tienen como objetivo imitar o incluso superar la inteligencia humana replicando sus funciones cognitivas, tales como razonar, aprender y resolver problemas.

Estos sistemas están entrenados para resolver problemas utilizando algoritmos, aprender de los datos y utilizar ese aprendizaje en el futuro. De esta manera, la inteligencia artificial va ganando "conocimiento".

Se reconocen cuatro etapas o niveles de inteligencia artificial:

*   Máquinas reactivas:
*   de Memoria Limitada:
*   de Teoría de la Mente:
*   de Autoconocimiento:

Los sistemas de inteligencia artificial tienen una particularidad: son para un uso específico. Es decir, no existen sistemas en los que se pueda hacer por ejemplo, reconocimiento de voz, jugar al ajedez y realizar predicciones de un tema específico. Cada inteligencia artificial tiene un objetivo bien definido. Si el objetivo es jugar al ajedrez, la inteligencia artificial será entrenada para esto solamente, por lo que recibirá una fuente grande de datos de ajedrez sobre la que forjará su aprendizaje.

El entrenamiento de una inteligencia artificial consiste en brindarle datos y analizar su comportamiento, para poder mejorarla. El sistema también aprenderá de sus errores, lo que acelera su entrenamiento y hace que funcione cada vez más acertadamente. Existen dos formas de entrenamiento: Machine Learning y Deep Learning.

=== Machine Learning

El Machine Learning o Aprendizaje Automático es un subcampo de la Inteligencia Artificial que se centra en dotar a las máquinas de la habilidad para identificar patrones en conjuntos de datos masivos y utilizar esos patrones para mejorar su rendimiento en tareas específicas.

Una de las características destacadas del "machine learning" es su capacidad para hacer predicciones precisas basadas en el análisis de datos, lo que lo convierte en una herramienta poderosa en una amplia variedad de aplicaciones, desde el procesamiento del lenguaje natural hasta el análisis de imágenes y la toma de decisiones automatizada.

Existen tres distintos modelos de predicción de Machine Learning: Aprendizaje supervisado, aprendizaje no supervisado y Deep Learning (aprendizaje reforzado).

==== Aprendizaje supervisado

El Aprendizaje supervisado implica usar ejemplos etiquetados para que el algoritmo se ajuste y aprenda patrones. Requiere intervención humana para clasificar y etiquetar datos. Ejemplo: filtrado de spam en correos, donde el algoritmo aprende de correos marcados como spam para identificar patrones y dirigir futuros correos similares a la carpeta de spam.

==== Aprendizaje no supervisado

En el modelo de aprendizaje no supervisado los datos que se incorporan no se etiquetan, ya que se desconoce su estructura. El algoritmo clasifica la información por sí solo. El aprendizaje no supervisado se clasifica en:

    * Clustering: Se agrupan datos sin conocimiento previo de su estructura en grupos con características similares. Los grupos obtenidos destacan patrones inherentes en los datos.

    * Reducción dimensional: Se procesan datos complejos al reducir redundancias y agrupar por características similares, generando información valiosa. Se aplica en estrategias de marketing para definir nichos de mercado, como al seleccionar clientes potenciales basados en comportamientos en redes sociales.

==== Deep Learning

Acá va la info de Deep Learning.

=== Proyectos de Data Science ó Big Data

==== Data Science vs Big Data, ¿estamos hablando de lo mismo?

Acá va la info de Data Science y Big Data.

==== ¿Cómo se gestiona un proyecto de Data Science o Big Data?

Acá ponemos sarasa.

== Conclusiones / dificultades

Acá ponemos más sarasa.
