= TP Inicial - Laboratorio de Construcción de Software
Ebertz Ximena <xebertz@campus.ungs.edu.ar>; Gross Pablo <pablorubengross@gmail.com>; López Gonzalo <gonzagonzalopez20@gmail.com>
v1, {docdate}
:toc:
:title-page:
:toc-title: Secciones
:numbered:
:source-highlighter: coderay
:tabsize: 4
:nofooter:


== Introducción

Investigación de conceptos: IA, Machine Learning, Deep Learning.

Investigación de proyectos de Data Science o Big Data.

== Objetivo

Acá va el objetivo.

== Repositorio

Para ir al repositorio del proyecto puede darle click https://github.com/ximeeb/ebertz-gross-lopez-tp-lcs.git[aquí].

== Desarrollo

=== Inteligencia Artificial (IA)

Antes de profundizar en el concepto de _Inteligencia Artificial_, debemos entender qué es un _agente_. La definición de este término es sencilla: un _agente_ es "alguien" hace algo. En el ámbito informático extendemos esta definción a la de _agentes computacionales_, que son programas que pueden operar autónomamente, percibir su entorno, persisitir durante un período de tiempo, adaptarse al cambio, y crear y perseguir metas. Por esto, podemos observar que no todos los sistemas informáticos son agentes.

En este contexto, conocemos como _Inteligencia Artificial_ o _IA_ a los *agentes computacionales racionales* existentes. Es decir, IA es cualquier software capaz de percibir su entorno, persistir durante un periodo de tiempo, adaptarse al cambio, y realizar cualquier cosa de la que es capaz un agente computacional, pero con la característica de que responde y actúa de manera racional, buscando la mejor opción para cada situación. Muchos de estos sistemas tienen como objetivo imitar o incluso superar la inteligencia humana, replicando sus funciones cognitivas tales como razonar, aprender y resolver problemas.

Dentro de la inteligencia artificial tenemos dos tipos: la _inteligencia artificial débil_, y la _inteligencia artificial fuerte_. La inteligencia artificial débil es la que no pretende parecerse a la inteligencia humana en su totalidad. Su finalidad es resolver un problema, y no más de uno. La inteligencia artificial fuerte es la que pretende parecerse o superar a la inteligencia humana, de forma que podría resolver cualquier problema que un ser humano puede resolver. Este tipo de inteligencia artificial en la actualidad se mantiene como hipotética.

Se reconocen cuatro etapas o niveles de desarrollo de inteligencia artificial:

*   *máquinas reactivas:* es un tipo de inteligencia artificial que no puede aprender ya que no utiliza memoria, pero sabe reaccionar ante ciertos estímulos, ya que lo tiene preprogramado.
*   *de memoria limitada:* es un tipo de inteligencia artificial que puede aprender, ya que utiliza memoria. Para generar su conocimiento se la entrena brindándole datos nuevos.
*   *de teoría de la mente:* es un tipo de inteligencia artificial que puede emular la mente humana, lo que le da la capacidad de tener sentimientos y emociones.
*   *de autoconocimiento:* es una inteligencia artificial de teoría de la mente con autoconocimiento.

Los sistemas de inteligencia artificial actuales tienen una particularidad: son para un uso específico. Es decir, son inteligencias artificiales débiles, y, en particular, de memoria limitada. No existen sistemas en los que se pueda hacer por ejemplo, reconocimiento de voz, jugar al ajedrez y realizar predicciones de un tema específico. Cada inteligencia artificial tiene un objetivo bien definido. Si el objetivo es jugar al ajedrez, la inteligencia artificial será entrenada para esto solamente, por lo que recibirá una fuente grande de datos de este tema sobre la que forjará su aprendizaje.

Las IA están entrenadas para resolver problemas utilizando algoritmos, aprender de los datos que se le brindaron, aprender de sus errores, y utilizar ese conocimiento en el futuro.

El entrenamiento de una inteligencia artificial consiste en brindarle datos y analizar su comportamiento, con la finalidad de ajustar sus parámetros y alcanzar cierto umbral de satisfacción. Existen dos formas de entrenamiento: _Machine Learning_ y _Deep Learning_.

=== Machine Learning

//podemos decir que es una forma de entrenamiento de IAs, para conectar con lo anterior?
El Machine Learning o Aprendizaje Automático es un subcampo de la Inteligencia Artificial que se centra en dotar a las máquinas de la habilidad para identificar patrones en conjuntos de datos masivos y utilizar esos patrones para mejorar su rendimiento en tareas específicas.

Una de las características destacadas del "machine learning" es su capacidad para hacer predicciones precisas basadas en el análisis de datos, lo que lo convierte en una herramienta poderosa en una amplia variedad de aplicaciones, desde el procesamiento del lenguaje natural hasta el análisis de imágenes y la toma de decisiones automatizada.

Existen tres distintos modelos de predicción de Machine Learning: Aprendizaje Supervisado, Aprendizaje No Supervisado y Deep Learning (Aprendizaje Reforzado).

==== Aprendizaje supervisado

El Aprendizaje supervisado implica usar ejemplos etiquetados para que el algoritmo se ajuste y aprenda patrones. Requiere intervención humana para clasificar y etiquetar datos. Ejemplo: filtrado de spam en correos, donde el algoritmo aprende de correos marcados como spam para identificar patrones y dirigir futuros correos similares a la carpeta de spam.

==== Aprendizaje no supervisado

En el modelo de aprendizaje no supervisado los datos que se incorporan no se etiquetan, ya que se desconoce su estructura. El algoritmo clasifica la información por sí solo. El aprendizaje no supervisado se clasifica en:

*   Clustering: Se agrupan datos sin conocimiento previo de su estructura en grupos con características similares. Los grupos obtenidos destacan patrones inherentes en los datos.

*   Reducción dimensional: Se procesan datos complejos al reducir redundancias y agrupar por características similares, generando información valiosa. Se aplica en estrategias de marketing para definir nichos de mercado, como al seleccionar clientes potenciales basados en comportamientos en redes sociales.

==== Deep Learning

El "Deep Learning" o "Aprendizaje Reforzado" es un subconjunto de lo que es "Machine learning" que igual que el ya mencionado propone el analisis de patrones para poder aplicarlas en diferentes tareas de manera mas eficiente. Este se distinge del "Machine learning" en el sentido que consume datos de manera cruda, sin tener que haber un paso intermedio para ordenar y recibir y procesar datos sin supervicion humana.

Esta manera de procesar datos permite el entrenamiento del modelo en cantidades grandes a traves de la automatizacion de la lectura de informacion que tiene a mano. A su ves esto agiliza el entrenamiento y permite un entrenamiento mas riguroso. Ejemplos de uso de esta teconología serían identificadores de fotos, rostros u texto. 

Este puede separarse en dos formas de aplicación:

*   Las redes neuronales convolucionales (CNN, por sus siglas en inglés). Esta se utiliza para el reconocimiento y clasificacion de imágenes y videos para identificar elementos que se encuentren en los mismos

*   Las redes neuronales recurrentes (RNN, por sus siglas en inglés). Esta se utiliza para el reconocimiento de vos y del lenguaje natural

=== Proyectos de Data Science ó Big Data

==== Data Science vs Big Data, ¿estamos hablando de lo mismo?

Acá va la info de Data Science y Big Data.

==== ¿Cómo se gestiona un proyecto de Data Science o Big Data?

Acá ponemos sarasa.

== Conclusiones / dificultades

Acá ponemos más sarasa.
